# Site
name: '.devlog'
description: '.devlog is a playground to write my thoughts down.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.jpg'
baseurl: 'https://hyeondnl.tk'
disqus: 'hyeondnl-tk'
email: 'hyeondnl@gmail.com'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    hyeon:
      name:           Hyeon Lee
      site:           https://hyeondnl.github.io
      bio:            "Hi, I am Hyeon Lee, the author of this webpage. I hope you like it!"
      email:          hyeondnl@gmail.com
      twitter:        https://twitter.com/hyeondnl
      avatar:         assets/images/avatar_lhd.png

    jane:
      name:           Jane
      site:           https://www.wowthemes.net
      avatar:         assets/images/avatar.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]